# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ipset_pb2 as ipset__pb2


class IpSetStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Set = channel.unary_unary(
        '/ipset.IpSet/Set',
        request_serializer=ipset__pb2.Request.SerializeToString,
        response_deserializer=ipset__pb2.Reply.FromString,
        )


class IpSetServicer(object):
  """The greeting service definition.
  """

  def Set(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IpSetServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=ipset__pb2.Request.FromString,
          response_serializer=ipset__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ipset.IpSet', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
